/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedInterviewPrepRouteImport } from './routes/_authenticated/interview-prep'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAiAnalysisRouteImport } from './routes/_authenticated/ai-analysis'
import { Route as AuthenticatedHistoryIdRouteImport } from './routes/_authenticated/history.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewPrepRoute =
  AuthenticatedInterviewPrepRouteImport.update({
    id: '/interview-prep',
    path: '/interview-prep',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAnalysisRoute = AuthenticatedAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryIdRoute = AuthenticatedHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ai-analysis': typeof AuthenticatedAiAnalysisRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/interview-prep': typeof AuthenticatedInterviewPrepRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ai-analysis': typeof AuthenticatedAiAnalysisRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/interview-prep': typeof AuthenticatedInterviewPrepRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/ai-analysis': typeof AuthenticatedAiAnalysisRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/interview-prep': typeof AuthenticatedInterviewPrepRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/history/$id': typeof AuthenticatedHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-analysis'
    | '/applications'
    | '/dashboard'
    | '/history'
    | '/interview-prep'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-analysis'
    | '/applications'
    | '/dashboard'
    | '/history'
    | '/interview-prep'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-analysis'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/interview-prep'
    | '/_authenticated/resume'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/_authenticated/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview-prep': {
      id: '/_authenticated/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof AuthenticatedInterviewPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-analysis': {
      id: '/_authenticated/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AuthenticatedAiAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/$id': {
      id: '/_authenticated/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AuthenticatedHistoryIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
  }
}

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryIdRoute: typeof AuthenticatedHistoryIdRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryIdRoute: AuthenticatedHistoryIdRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAnalysisRoute: typeof AuthenticatedAiAnalysisRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedInterviewPrepRoute: typeof AuthenticatedInterviewPrepRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAnalysisRoute: AuthenticatedAiAnalysisRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedInterviewPrepRoute: AuthenticatedInterviewPrepRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
